apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/HaitamDevOps/microservices-demo.git
    targetRevision: main
    path: k8s-manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
